import tkinter as tk
from tkinter import ttk

def show_register(canvas, callbacks):
    notebook = ttk.Notebook(canvas)
    rider_tab = ttk.Frame(notebook)
    notebook.add(rider_tab, text="Rider")
    rider_username_label = ttk.Label(rider_tab, text="Username:")
    rider_username_label.pack(padx=20, pady=5)
    rider_username_entry = ttk.Entry(rider_tab)
    rider_username_entry.pack(padx=20, pady=5)
    rider_password_label = ttk.Label(rider_tab, text="Password:")
    rider_password_label.pack(padx=20, pady=5)
    rider_password_entry = ttk.Entry(rider_tab, show="*")
    rider_password_entry.pack(padx=20, pady=5)
    rider_register_button = ttk.Button(rider_tab, text="Register as Rider", command=lambda: callbacks["register_rider"](rider_username_entry.get(), rider_password_entry.get()))
    rider_register_button.pack(pady=20)
    passenger_tab = ttk.Frame(notebook)
    notebook.add(passenger_tab, text="Passenger")
    passenger_username_label = ttk.Label(passenger_tab, text="Username:")
    passenger_username_label.pack(padx=20, pady=5)
    passenger_username_entry = ttk.Entry(passenger_tab)
    passenger_username_entry.pack(padx=20, pady=5)
    passenger_password_label = ttk.Label(passenger_tab, text="Password:")
    passenger_password_label.pack(padx=20, pady=5)
    passenger_password_entry = ttk.Entry(passenger_tab, show="*")
    passenger_password_entry.pack(padx=20, pady=5)
    passenger_register_button = ttk.Button(passenger_tab, text="Register as Passenger", command=lambda: callbacks["register_passenger"](passenger_username_entry.get(), passenger_password_entry.get()))
    passenger_register_button.pack(pady=20)
    notebook.pack(expand=1, fill="both")
